/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationsIndexRouteImport } from './routes/automations.index'
import { Route as AutomationsIdEditRouteImport } from './routes/automations.$id.edit'
import { Route as AuthInstagramCallbackRouteImport } from './routes/auth.instagram.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutomationsRoute,
} as any)
const AutomationsIdEditRoute = AutomationsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AutomationsRoute,
} as any)
const AuthInstagramCallbackRoute = AuthInstagramCallbackRouteImport.update({
  id: '/auth/instagram/callback',
  path: '/auth/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/automations/': typeof AutomationsIndexRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/automations/$id/edit': typeof AutomationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/automations': typeof AutomationsIndexRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/automations/$id/edit': typeof AutomationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/automations/': typeof AutomationsIndexRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/automations/$id/edit': typeof AutomationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/automations/'
    | '/auth/instagram/callback'
    | '/automations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/automations'
    | '/auth/instagram/callback'
    | '/automations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/contacts'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/automations/'
    | '/auth/instagram/callback'
    | '/automations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AuthInstagramCallbackRoute: typeof AuthInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/': {
      id: '/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof AutomationsRoute
    }
    '/automations/$id/edit': {
      id: '/automations/$id/edit'
      path: '/$id/edit'
      fullPath: '/automations/$id/edit'
      preLoaderRoute: typeof AutomationsIdEditRouteImport
      parentRoute: typeof AutomationsRoute
    }
    '/auth/instagram/callback': {
      id: '/auth/instagram/callback'
      path: '/auth/instagram/callback'
      fullPath: '/auth/instagram/callback'
      preLoaderRoute: typeof AuthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutomationsRouteChildren {
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  AutomationsIdEditRoute: typeof AutomationsIdEditRoute
}

const AutomationsRouteChildren: AutomationsRouteChildren = {
  AutomationsIndexRoute: AutomationsIndexRoute,
  AutomationsIdEditRoute: AutomationsIdEditRoute,
}

const AutomationsRouteWithChildren = AutomationsRoute._addFileChildren(
  AutomationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRouteWithChildren,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AuthInstagramCallbackRoute: AuthInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
